version: '3.8'

services:
  web:
    image: ervincaravaliibarra/webbackend:latest
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    deploy:
      replicas: 1  
      restart_policy:
        condition: any
    env_file:
      - .env  
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: ervincaravaliibarra/dbbackend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - .env  
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    image: ervincaravaliibarra/frontend:latest
    deploy:
      replicas: 1 
      restart_policy:
        condition: any
    env_file:
      - .env 
    ports:
      - "5173:5173"
    networks:
      - backend

  tests:
    image: ervincaravaliibarra/webbackend:latest
    deploy:
      replicas: 1  
      restart_policy:
        condition: any
    env_file:
      - .env 
    command: sh -c "locust -f locust/locustfile.py"

    depends_on:
      - web
    ports:
      - "8090:8089" 
    networks:
      - backend   

networks:
  backend:

volumes:
  db_data:
